version: '3'
services:
  server:
    env_file:
      - .env
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app